const $=q=>document.querySelector(q), $$=q=>document.querySelectorAll(q);
const content=window.INVITATION_CONTENT || {secrets:{},audio:{volume:.42}};
const storageKey='ratem-tonight-london-secrets-v2';
let found=new Set(JSON.parse(localStorage.getItem(storageKey)||'[]'));
const music=$('#bgMusic'), musicToggle=$('#musicToggle');
document.title=`${content.recipient || 'רתם'}… ❤️`;
function renderSecretCount(){ $('#secretCount').textContent=`${found.size}/5`; }
function playMusic(){music.volume=content.audio?.volume ?? .42; music.play().then(()=>{musicToggle.classList.add('playing');musicToggle.setAttribute('aria-pressed','true');musicToggle.querySelector('span').textContent='צליל פעיל'}).catch(()=>{musicToggle.querySelector('span').textContent='הפעילי צליל'});} 
musicToggle.onclick=()=>{if(music.paused)playMusic();else{music.pause();musicToggle.classList.remove('playing');musicToggle.setAttribute('aria-pressed','false');musicToggle.querySelector('span').textContent='צליל כבוי'}};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function haptic(p=12){if(navigator.vibrate) navigator.vibrate(p)}
function burst(x=innerWidth/2,y=innerHeight/2,n=34){for(let i=0;i<n;i++){let e=document.createElement('i');e.className='burst';e.textContent=Math.random()>.22?'♥':'🇬🇧';e.style.cssText=`left:${x}px;top:${y}px;--x:${(Math.random()-.5)*420}px;--y:${(Math.random()-.5)*420}px;--r:${Math.random()*720-360}deg;animation-delay:${Math.random()*.08}s`;document.body.append(e);setTimeout(()=>e.remove(),1300)}}
$('#listen').onclick=e=>{playMusic();haptic(25);burst(e.clientX,e.clientY,55);document.body.classList.add('started');$('#scrollHint').classList.add('show');setTimeout(()=>document.querySelector('.one').scrollIntoView({behavior:reduced?'auto':'smooth'}),550)};
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('seen')}),{threshold:.25});$$('.reveal-on-scroll').forEach(e=>observer.observe(e));
addEventListener('scroll',()=>{let p=Math.min(1,scrollY/(document.documentElement.scrollHeight-innerHeight));$('#progressLine').style.height=`${p*100}%`;$('#progressHeart').textContent=p>.96?'♥':p>.42?'♥':'♡';document.body.style.setProperty('--scroll',p);},{passive:true});
function secret(el){let id=el.dataset.secret;if(found.has(id)){ $('#modalText').textContent='את הסוד הזה כבר מצאת 😏'; $('#modal').classList.add('open'); return; } found.add(id);localStorage.setItem(storageKey,JSON.stringify([...found]));renderSecretCount();haptic(18);burst(el.getBoundingClientRect().left+20,el.getBoundingClientRect().top+20,17);$('#modalText').textContent=content.secrets[id] || el.dataset.message;$('#modal').classList.add('open');if(found.size===5)setTimeout(unlock,600)}$$('.secret').forEach(el=>{el.addEventListener('click',()=>secret(el));el.addEventListener('keydown',e=>e.key==='Enter'&&secret(el))});function closeModal(){$('#modal').classList.remove('open')} $('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});renderSecretCount();
function unlock(){const c=$('#modalText');c.innerHTML='🔓<br><b>ACHIEVEMENT UNLOCKED</b><br>LONDON WITH YOU<br><small>September is going to be dangerous… 😈🇬🇧</small>';burst(innerWidth/2,innerHeight/2,55)}
$$('[data-answer]').forEach(b=>b.onclick=e=>{let trouble=b.dataset.answer==='trouble';haptic([40,55,45]);burst(e.clientX,e.clientY,95);$('#answerScreen').classList.add('open',trouble?'trouble':'sweet');$('#answerContent').innerHTML=trouble?'<div class="emoji-line">😈🔥😈🔥😈</div><h2>ידעתי שבגלל זה אני אוהב אותך <em>😈♥</em></h2><p>19:00.<br><b>Don’t be late 😈</b></p>':'<h2>ידעתי <em>♥</em></h2><p>19:00. נתראה הערב.<br><em>♥</em></p>';setTimeout(()=>{$('#answerContent').innerHTML+='<small class="after">רגע…<br>חשבת שזה נגמר?<br><b>😏</b><br><i>🇬🇧</i><br>September…</small>'},3600)});
const c=$('#particles'),x=c.getContext('2d');let pts=Array.from({length:25},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,s:Math.random()*2+1,v:Math.random()*.35+.08}));function draw(){c.width=innerWidth;c.height=innerHeight;function f(){x.clearRect(0,0,c.width,c.height);x.fillStyle='#fa345d';pts.forEach(p=>{p.y-=p.v;if(p.y<0){p.y=innerHeight;p.x=Math.random()*innerWidth}x.globalAlpha=.22;x.font=`${p.s*8}px serif`;x.fillText('♥',p.x,p.y)});if(!reduced)requestAnimationFrame(f)}f()}draw();
